spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:8000/adam?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Password!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    default_batch_fetch_size: 100
    open-in-view: true

logging:
  level:
    project.adam.controller: debug
    org.hibernate.SQL: debug